name: dco

on:
  pull_request:

permissions:
  contents: read

jobs:
  dco:
    name: dco
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: ./bin/verify dco
        env:
          DCO_BASE: ${{ github.event.pull_request.base.sha }}
          DCO_HEAD: ${{ github.event.pull_request.head.sha }}
